# Generated by Django 4.0.3 on 2022-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=20)),
                ('predador', models.CharField(max_length=4)),
                ('venenoso', models.CharField(max_length=4)),
                ('domestico', models.CharField(max_length=4)),
            ],
        ),
    ]
